### ISSUE TITLE
Blocklist is 2x more than it should be.

### ISSUE THREAD

**Issue by PMJeffery** [ZachChristensen28/TA-pihole_dns#33]
**Describe the bug**
When using the API request to pihole and saving to the lookup file,  pihole_blocklist_lookup, it shows twice as many lists than actually subscribed to.

Input collects *.sha1 hash suffix for each list subscribed to.

**To Reproduce**
N/A

**Expected behavior**
Only collect actual list of subscribed block lists, ignoring sha1 suffix

**Screenshots**
Splunk Report
![image](https://user-images.githubusercontent.com/20860518/125114930-a1515b80-e0b8-11eb-9645-0d46cd2de8ff.png)

![image](https://user-images.githubusercontent.com/20860518/125115919-f93c9200-e0b9-11eb-83d5-c1811c7c04c4.png)

Pihole Block List:
![image](https://user-images.githubusercontent.com/20860518/125115404-49672480-e0b9-11eb-8c07-2ea9b67a1574.png)

**Version (please complete the following information):**
 - Splunk Version: [e.g.8.2.1]
 - Pi-hole Version [e.g. core=5.3.1, FTL=5.8.1]
 - TA_pihole_dns Version [e.g. 1.3.1]

**Additional context**
I don't believe that the sha1 suffix is needed even if Pihole produces it

**Comment by PMJeffery** [comment]
probably the simpliest thing to do is edit the Pihole App (Blocklist Activity Dashboard) to this:

```
| inputlookup pihole_blocklist_lookup
| search blocklist!=*sha1
| stats dc(blocklist) as blocklist_count
```

**Comment by ZachChristensen28** [comment]
the `pihole_blocklist_lookup` is populated by the scripted input `pihole_lists.sh` which is now deprecated since it only looks at the cached domains. When Pi-hole releases Pi-hole version 6, they will allow to retrieve this information from the API. The next releases of this add-on will use this information to keep the lookup updated. You can preview this version by looking at the branch `pihole-v6-api` but this will take some setup with your pi-hole to work correctly.
